export enum CompanyEnums {
  ticker = "Ticker",
  name = "Name",
  legal_name = "Legal name",
  stock_exchange = "Stock exchange",
  short_description = "Short description",
  long_description = "Long description",
  company_url = "Web",
  business_address = "Business address",
  business_phone_no = "Business phone",
  entity_legal_form = "Entity legal form",
  latest_filing_date = "Latest filing date",
  inc_country = "Inc country",
  employees = "Employees",
  sector = "Sector",
  industry_category = "Industry category",
  industry_group = "Industry group",
  first_stock_price_date = "First stock price date",
  last_stock_price_date = "Last stock price date",
  thea_enabled = "Thea enabled",
  legacy_sector = "Legacy sector",
  legacy_industry_category = "Legacy industry category",
  legacy_industry_group = "Legacy industry group"
}
